# Generated by Django 3.1.2 on 2020-10-31 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('nro_doc_cliente', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre_cliente', models.CharField(max_length=40)),
                ('apellido_paterno', models.CharField(max_length=30)),
                ('apellido_materno', models.CharField(max_length=30)),
                ('sexo', models.CharField(max_length=20)),
                ('telefono_field', models.CharField(db_column='telefono ', max_length=20)),
                ('correo_electronico', models.CharField(max_length=50, unique=True)),
                ('ocupacion', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegistroCliente',
            fields=[
                ('usuario', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('clave_field', models.CharField(db_column='clave ', max_length=30)),
            ],
            options={
                'db_table': 'registro_cliente',
                'managed': False,
            },
        ),
    ]
