# Generated by Django 3.1.2 on 2020-11-08 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_auto_20201104_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id_proyecto', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_proyecto', models.CharField(max_length=30)),
                ('tipo_servicio', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=400)),
            ],
            options={
                'db_table': 'proyecto',
                'managed': False,
            },
        ),
    ]
